name       : libplatform
version    : 1.0.10
release    : 1
source     :
    - https://github.com/Pulse-Eight/platform/archive/1.0.10.tar.gz : 6ba3239cb1c0a5341efcf9488f4d3dfad8c26d6b2994b2b2247e5a61568ab5cd
license    : GPL-2.0
summary    : Platform support library used by libCEC and binary add-ons for Kodi
description: |
    Platform support library used by libCEC and binary add-ons for Kodi
builddeps  :
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
