name       : libplatform
version    : 2.1.0.1
release    : 2
source     :
    - https://github.com/Pulse-Eight/platform/archive/p8-platform-2.1.0.1.tar.gz : 064f8d2c358895c7e0bea9ae956f8d46f3f057772cb97f2743a11d478a0f68a0
license    : GPL-2.0
component  : desktop.multimedia
summary    : Platform support library used by libCEC and binary add-ons for Kodi.
description: |
    Platform support library used by libCEC and binary add-ons for Kodi.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
